"""add investments goals and recurring contributions

Revision ID: 0d39007b5bff
Revises: 0d543d4b20af
Create Date: 2026-10-01 09:20:08.471195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d39007b5bff'
down_revision: Union[str, Sequence[str], None] = '0d543d4b20af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('investment_type', sa.Enum('STOCK', 'ETF', 'RETIREMENT_401K', 'ROTH_IRA', 'REAL_ESTATE', 'OTHER', name='investmenttype'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('shares', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('current_price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('manual_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('manual_apy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projection_years', sa.Integer(), nullable=True),
    sa.Column('target_projected_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('linked_account_id', sa.Integer(), nullable=True),
    sa.Column('manual_apy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uninvested_cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_uninvested_account_date')
    )
    op.create_table('goal_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='recurringfrequency'), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('holding_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['savings_goals.id'], ),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_investments')
    op.drop_table('goal_contributions')
    op.drop_table('uninvested_cash')
    op.drop_table('savings_goals')
    op.drop_table('holdings')
    # ### end Alembic commands ###
