"""add transaction is_reviewed flag

Revision ID: 0d543d4b20af
Revises: 427b93a6cb21
Create Date: 2026-09-20 01:48:48.685989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d543d4b20af'
down_revision: Union[str, Sequence[str], None] = '427b93a6cb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here: SQLite (and most DBs) can't add a
    # NOT NULL column to a table with existing rows without one. Existing
    # transactions are treated as unreviewed, same as the model default.
    op.add_column(
        'transactions',
        sa.Column('is_reviewed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_reviewed')
    # ### end Alembic commands ###
