"""add monthly savings summary table

Revision ID: 427b93a6cb21
Revises: cf7ecda925aa
Create Date: 2026-09-20 01:28:54.230323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427b93a6cb21'
down_revision: Union[str, Sequence[str], None] = 'cf7ecda925aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_savings_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('contributed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['savings_allocations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id', 'year', 'month', name='uq_allocation_year_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_savings_summaries')
    # ### end Alembic commands ###
