"""replace account is_manual with parser_type

Revision ID: 8862519ed01c
Revises: b7e6d0683bf2
Create Date: 2026-09-19 21:49:31.153808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8862519ed01c'
down_revision: Union[str, Sequence[str], None] = 'b7e6d0683bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('parser_type', sa.String(length=40), nullable=True))
    op.drop_column('accounts', 'is_manual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_manual', sa.BOOLEAN(), nullable=False))
    op.drop_column('accounts', 'parser_type')
    # ### end Alembic commands ###
